{{- if .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
data:
  # The credentials used with the "power user" service principal that will be
  # making the Azure API calls to validate things about the "target" service
  # principal.
  AZURE_TENANT_ID: {{ .Values.auth.tenantId | b64enc }}
  AZURE_CLIENT_ID: {{ .Values.auth.clientId | b64enc }}
  AZURE_CLIENT_SECRET: {{ .Values.auth.clientSecret | b64enc }}
  # TODO
  # This used to be where AWS session token was taken into account. This concept
  # might apply to Azure too. If it does, we need to keep this and change it to
  # the Azure equivalent. If not, we should remove this to keep things as simple
  # as possible.
  # {{- if .Values.auth.overrideTbd }}
  # AZURE_OVERRIDE_TBD: {{ .Values.auth.overrideTbd | b64enc }}
  # {{- end }}
{{- end }}
