auth:
  # The name of the secret to look for the config in. Or, the name of the
  # secret to be created and for the credentials to be provided to if a secret
  # does not yet exist and createSecret is not overriden to false.
  secretName: azure-creds
  # Allows the plugin to automatically create the secret containing the
  # credentials if it does not yet exist.
  createSecret: true
  # The tenant ID for the application in Microsoft Entra.
  tenantId: ""
  # The client ID associated with the tenant. Also known as application ID.
  clientId: ""
  # The client secret associated with the tenant.
  clientSecret: ""
