apiVersion: validation.spectrocloud.labs/v1alpha1
kind: AzureValidator
metadata:
  name: azurevalidator-rbac-one-permission-set-role-custom-actions-specified-and-missing
spec:
  auth:
    implicit: false
    secretName: azure-creds
  rbacRules:
  - principalId: "a83574a7-53ef-4b37-b85e-99f956f0985a"
    permissionSets:
    - role: "d2dd3116-04f5-4c40-944a-c28eeeed6a2e" # MyCustomRole
      scope: "/subscriptions/9b16dd0b-1bea-4c9a-a291-65e6f44c4745"
      actions:
      - "Microsoft.Compute/virtualMachines/read" # role has this action
      - "Microsoft.Compute/virtualMachines/write" # but not this one