apiVersion: validation.spectrocloud.labs/v1alpha1
kind: AzureValidator
metadata:
  name: azurevalidator-rbac-invalid2
spec:
  auth:
    implicit: false
    secretName: azure-creds
  rbacRules:
  - principalId: "a83574a7-53ef-4b37-b85e-99f956f0985a"
    permissionSets:
    # Permission set is invalid because there are no control Actions and no DataActions to be validated
    - scope: "/subscriptions/9b16dd0b-1bea-4c9a-a291-65e6f44c4745"
      actions: []
      dataActions: []
